<?php 
/**
 *Implementing hook_menu().
 */
function wwex_shipments_detail_report_menu(){
	 
	$items['shipment-detail-report'] = array(
		'title' => 'Shipments Detail Report',
		'access callback' => TRUE,
    'weight' => 0,  
    'menu_name' => 'menu-shipment-reports-menu',
    'type' => MENU_NORMAL_ITEM,
	); 
	
  return $items;
}

/*
 * Implementation of hook_views_api()
 */
function wwex_shipments_detail_report_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_theme().
 */
function wwex_shipments_detail_report_theme() {
	return array(
		'views_view__shipment_detail_report' => array(
			'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
			'template' => 'views-view--shipment-detail-report',
			'base hook' => 'views_view',
			'path' => drupal_get_path('module', 'wwex_shipments_detail_report') . '/theme',
		),
	);
}


// hook_views_pre_render()
function wwex_shipments_detail_report_views_pre_render(&$view) {
	// Scramble the order of the rows shown on this result page.
	// Note that this could be done earlier, but not later in the view execution
	// process.
	if( $view->name == 'shipment_detail_report' ){
		
		// update total values
		if( isset( $view->totals )){
			
			// first we get total customer rate (Total Retial Price)
			$total_customer_rate = isset($view->totals['field_customer_rate']) ? strip_tags($view->totals['field_customer_rate']) : 0;

			$total_margin = isset($view->totals['expression_1']) ? $view->totals['expression_1'] : 0;
			
			// calculate total marin %
			$margin_percentage = $total_customer_rate > 0 ? ($total_margin / $total_customer_rate) * 100 : 0;
			
			// replce total customer rate
			if( isset($view->totals['field_customer_rate_1']) )
				$view->totals['field_customer_rate_1'] = '$' . number_format($total_customer_rate, 2, '.', ',');
				
			// replce total margin % rate
			if( isset($view->totals['expression_2']) )
				$view->totals['expression_2'] = number_format($margin_percentage, 2, '.', '') . '%';
				
		}
		
		// change values per row
		// it is toatl of tiers e.g for tier A or B or C
		if( isset($view->style_plugin->rendered_fields) ){
			$rendered_fields = &$view->style_plugin->rendered_fields;
			
			foreach($rendered_fields as $count => $fields){
				
				// get revenue and margin per row
			    $total_customer_rate_pr = isset($fields['field_customer_rate']) ? $fields['field_customer_rate'] : 0;
				$total_margin_pr = isset($fields['expression_1']) ? $fields['expression_1'] : 0;
				
				// calculate margin % per row
				$margin_percentage_pr = $total_customer_rate_pr > 0 ? ($total_margin_pr / $total_customer_rate_pr) * 100 : 0;
				// change margin % per row 
				if( isset($fields['expression_2']) )
					$view->style_plugin->rendered_fields[$count]['expression_2'] = number_format($margin_percentage_pr, 2, '.', '') . '%';
				
			}
				
		}
	}
}

// get user franchise
function wwex_shipments_detail_report_user_franchise(){
  global $user;

  if ($user->uid > 0) {
    $user_obj = user_load($user->uid); 
    $user_franchise_nid = isset($user_obj->field_user_franchise['und'][0]['nid']) ? $user_obj->field_user_franchise['und'][0]['nid'] : 0;
  }
  
  return $user_franchise_nid;
}

// get all sales rep
function wwex_shipments_detail_report_list_sales_rep(){
  global $user;
  $sales_rep = array();
  //$sales_rep[] = 'Select Sale Rep';

  if ($user->uid > 0) {
    $user_obj = user_load($user->uid); 
    $user_franchise_nid = isset($user_obj->field_user_franchise['und'][0]['nid']) ? $user_obj->field_user_franchise['und'][0]['nid'] : 0;
  }
  $query = "SELECT DISTINCT fr.entity_id, usr.name 
  FROM field_data_field_user_franchise fr,users_roles ur, node n, users usr 
  WHERE fr.field_user_franchise_nid = :franchise_nid AND (fr.entity_id = ur.uid AND ur.rid != '7') 
  AND fr.entity_id = n.uid AND fr.entity_id = usr.uid AND n.type = 'shipment'
  ";

  $res = db_query($query,  array(':franchise_nid' => $user_franchise_nid));

  if( !empty($res) ){
    foreach ( $res as $item ) {
	  $sales_rep[] = $item->entity_id;
    }
  }
  
  return $sales_rep;
}

/**
 * Implementing hook_views_query_alter().
 */ 
function wwex_shipments_detail_report_views_query_alter(&$view, &$query) {
	if ($view->name == 'shipment_detail_report' && $view->current_display == 'shipment_detail_report') {	
		
		// add sales rep filter
		if( function_exists('wwex_shipments_detail_report_list_sales_rep')) {
		  $sales_rep = wwex_shipments_detail_report_list_sales_rep();
		  if( !empty($sales_rep) ){
		    $query->where[1]['conditions'][] = array(
				'field' => 'node.uid',
				'value' => $sales_rep,
				'operator' =>'IN' 
			);
		  }
		  // if sales_rep filter is selected, we have to hide main display
		  // so we are adding some condition which is not
		  // present, so it will automatic hide view due to no result found
		  else {
			$query->where[1]['conditions'][] = array(
				'field' => 'node.uid',
				'value' => -999,
				'operator' =>'=' 
		    );
		  }
		}
		
		// add user franchise filter
		if( function_exists('wwex_shipments_detail_report_user_franchise')) {
		  $user_franchise = wwex_shipments_detail_report_user_franchise();
		  
		  // add franchis field relation in query
		  $join = new views_join;
		  $join->construct('field_data_field_shipment_franchise','node','nid','entity_id');
          $view->query->add_relationship('field_data_field_shipment_franchise',$join,'node');
	
		  if( !empty($user_franchise) ){
		    $query->where[1]['conditions'][] = array(
				'field' => 'field_data_field_shipment_franchise.field_shipment_franchise_nid',
				'value' => $user_franchise,
				'operator' =>'=' 
			);
		  }
		  // if user has no franchise, hide view
		  else {
			$query->where[1]['conditions'][] = array(
				'field' => 'field_data_field_shipment_franchise.field_shipment_franchise_nid',
				'value' => -999,
				'operator' =>'=' 
		    );
		  }
		}
	}
}