<?php

/*
 * Implementation of hook_views_api()
 */
function wwex_revenue_report_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_theme().
 */
function wwex_revenue_report_theme() {
  return array(
    'views_view__revenue_report' => array(
    'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
    'template' => 'views-view--revenue-report',
    'base hook' => 'views_view',
    'path' => drupal_get_path('module', 'wwex_revenue_report') . '/theme',
		),
	);
}
// hook_views_pre_render()
function wwex_revenue_report_views_pre_render(&$view) {
  // Scramble the order of the rows shown on this result page.
  // Note that this could be done earlier, but not later in the view execution
  // process.
  
  if ( $view->name == 'revenue_report' ) {
    
    // re calculate totals
    if ( isset( $view->totals )) {
			
			// get total booking fee (Booking fee hidden)
      $total_booking_fee = isset($view->totals['field_shipment_booking_fee']) ? strip_tags($view->totals['field_shipment_booking_fee']) : 0;
			// get total shipts count(nid)
      $total_shipts = isset($view->totals['nid']) ? str_replace(',', '', strip_tags($view->totals['nid'])) : 0;
			if ( isset($view->totals['nid']) )
				$view->totals['php'] = $total_shipts;	
    }
  }
}