<?php

/**
* @file
* function wwex_access_user_has_role($roles)
* function wwex_access_clean_input($input, $int = FALSE, $str = FALSE)
*/

// Check user role
function wwex_access_user_has_role($roles) {
  if (user_is_logged_in()) {
  
  global $user;
  if (in_array('administrator', $user->roles)) {
    return TRUE;
  }
  
  foreach ($roles as $role) {
  
  if (in_array($role, $user->roles)) {
    return TRUE;
  }
  }
  }
  else {
  return FALSE;
  }
}

/*
* Clean input
*/
function wwex_access_clean_input($input, $int = FALSE, $str = FALSE) {
//if the variable is an array, recurse into it
if (is_array($input) && !empty($input)) {
//for each element in the array...
  foreach ($input as $key => $val) {
  //...clean the content of each variable in the array
  $input[$key] = wwex_access_clean_input($val, $int, $str);
  }
  
  //return clean array
  return $input;
  }
  else {
  $input = filter_var($input, FILTER_SANITIZE_STRING);
  $input = trim($input);
  $input = stripslashes($input);
  $input = strip_tags($input);
  $input = str_replace(array('‘', '’', '“', '”'), array("'", "'", '"', '"'), $input);

// only int value
if ($int)
  $input = preg_replace("/[^0-9\s]/", "", $input);
  
  // only string values	
  if ($str)
  $input = preg_replace("/[^a-zA-Z\s]/", "", $input);
  
  return $input;
  }
}