<?php

/**
* @file
*  function wwex_views_field_load_status_views_api() for wwex_views_field_load_status_views module.
*/

/**
 * Implementation of hook_views_api().
 */
function wwex_views_field_load_status_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'wwex_views_field_load_status') . '/views',
  );
}

//$options = taxonomy_term_load(23);
//print_r($options);