<?php 

/**
* @file
* hook_preprocess_views_aggregator_results_table() is use for wwex_market_performance_report module table aggregation.
* wwex_market_performance_report_list_sales_rep() is use to list all sale rep for wwex_market_performance_report module.
* hook_views_query_alter() is use for sale rep report.
*/

// hook_views_pre_render()
function wwex_market_performance_report_views_pre_render(&$view) {
  // Scramble the order of the rows shown on this result page.
  // Note that this could be done earlier, but not later in the view execution
  // process.
  
  if ( $view->name == 'market_performance_report' ) {
    
    // re calculate totals
    if ( isset( $view->totals )) {
			
			// get total booking fee (Booking fee hidden)
      $total_booking_fee = isset($view->totals['field_shipment_booking_fee']) ? strip_tags($view->totals['field_shipment_booking_fee']) : 0;
			// get total shipts count(nid)
      $total_shipts = isset($view->totals['nid']) ? str_replace(',', '', strip_tags($view->totals['nid'])) : 0;
			
			// calculate total avg booking fee
			$total_avg_booking_fee = $total_booking_fee ? ($total_booking_fee / $total_shipts) : 0;
			// calculate total performance
			$total_performance = $total_avg_booking_fee ? ($total_avg_booking_fee / 55) * 100 : 0;
      
      // replce total booking fee (Booking fee)
      if ( isset($view->totals['field_shipment_booking_fee_3']) )
        $view->totals['field_shipment_booking_fee_3'] = '$' . number_format($total_booking_fee, 2, '.', '');
				
      // replce total avg booking fee (AVG)
      if ( isset($view->totals['field_shipment_booking_fee_1']) )
        $view->totals['field_shipment_booking_fee_1'] = '$' . number_format($total_avg_booking_fee, 2, '.', '');
				
      // replce total avg booking fee (AVG Hidden)
      if ( isset($view->totals['field_shipment_booking_fee_2']) )
        $view->totals['field_shipment_booking_fee_2'] = '$' . number_format($total_avg_booking_fee, 2, '.', '');
				
      // replce total performance (Performance)
      if ( isset($view->totals['expression']) )
        $view->totals['expression'] = number_format($total_performance, 2, '.', '') . '%';
				
    }
		
		// change values per row
    // it is toatl of tiers e.g for tier A or B or C
    if ( isset($view->style_plugin->rendered_fields) ) {
      $rendered_fields = &$view->style_plugin->rendered_fields;
      
			foreach ($rendered_fields as $count => $fields) {
			 
				// get booking fee avg (AVG hidden)
				$booking_fee_avg = isset($fields['field_shipment_booking_fee_2']) ? $fields['field_shipment_booking_fee_2'] : 0;
				// calculate total performance
				$performance = $booking_fee_avg ? ($booking_fee_avg / 55) * 100 : 0;
				
				// replce performance (Performance)
				if ( isset($fields['expression']) )
					$view->style_plugin->rendered_fields[$count]['expression'] = number_format($performance, 2, '.', '') . '%';
	
			}

     }
		
    
  }
}

/*
 * Implementation of hook_views_api()
 */
function wwex_market_performance_report_views_api() {
  return array('api' => 3.0);
}


/**
 * Implements hook_theme().
 */
function wwex_market_performance_report_theme() {
  return array(
    'views_view__market_performance_report' => array(
      'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view--market-performance-report',
      'base hook' => 'views_view',
      'path' => drupal_get_path('module', 'wwex_market_performance_report') . '/theme',
    ),
  );
}